
# Background --------------------------------------------------------------

# I have a lot of downloaded songs and podcasts on spotify. I want to remove
# them but the UI is very slow. I'll use the API to automatically remove them.

# This is a 2 step process: first get a list of all the tracks in my library
# (one app to do this) and then remove it (another app to do this). 2 apps are
# used because the scope/permission for the first one is limited (but well
# documented).

# This script is open source, but requires a separate script with the user's
# credentials to actually. The required variables are outlined in this script.

# Housekeeping ------------------------------------------------------------

#devtools::install_github('charlie86/spotifyr')
library(spotifyr)
library(dplyr)

source(file = "user_details.R")
# Client ID provided by spotify
# id <- "client ID" 
# Client Secret also provided by spotify
# secret <- "client secret"

Sys.setenv(SPOTIFY_CLIENT_ID = id)
Sys.setenv(SPOTIFY_CLIENT_SECRET = secret)

access_token <- get_spotify_access_token()

# my_id <- 'my_id'

# https://developer.spotify.com/console/delete-current-user-saved-tracks/?ids=4iV5W9uYEdYUVa79Axb7Rh
# Make sure the access token is up to date, LOL. 
#access_token <- "access token"

# List all the tracks in my library
my_tracks <- get_my_saved_tracks(limit = 50)
my_tracks %>% View()

# Loop through the library and remove the tracks 

for(i in 1:50){
  
  print(i)
  track_id = my_tracks$track.id[i]
  base_url <- 'https://api.spotify.com/v1/me/tracks'
  params <- list(
  # This is an OAutho token, it was generated by a different app because the
  # above steps did not have the required permission.
  # https://developer.spotify.com/console/delete-current-user-saved-tracks/?ids=4iV5W9uYEdYUVa79Axb7Rh
  access_token = access_token,
    ids = paste0(track_id, collapse = ',')
  )
  res <- httr::RETRY('DELETE', base_url, query = params, encode = 'json')  
  
}

  